# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: test
  encoding: utf8
  host: localhost
  password: 26572827
  username: root

production:
  adapter: mysql2
  database: test
  encoding: utf8
  host: localhost
  password: 26572827
  username: root

test:
  adapter: mysql2
  database: test
  encoding: utf8
  host: localhost
  password: 26572827
  username: root
